### ISSUE TITLE
[PE-D][Tester C] Unable to fetch transactions for different users with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-3/tp#165]
Steps to recreate the bug:
Create multiple users with the same name
Create a transaction
Find transaction by customer

![image.png](https://raw.githubusercontent.com/cnivedit/ped/main/files/512f2a08-3d8a-4c7e-a140-003ea75351ac.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: cnivedit/ped#5

**Comment by tkhahns** [comment]
No one has the same name now. Resolved
