### ISSUE TITLE
[PE-D][Tester E]  maybe can make name case-insensitive? 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T11-3/tp#180]
noted partial name does not work, this should be correct, because name should be exact

but maybe can make name case-insensitive? 

![image.png](https://raw.githubusercontent.com/kaboomzxc/ped/main/files/7ad01361-9310-4923-a361-05199540e7bf.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: kaboomzxc/ped#11

**Comment by SemiColonKen** [comment]
resolved
