### ISSUE TITLE
[PE-D][Tester E] it seems like duplicate transactions not handled 

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T11-3/tp#181]
it seems like duplicate transactions not handled 

![image.png](https://raw.githubusercontent.com/kaboomzxc/ped/main/files/5cd40d0c-e3c2-430d-8a95-58df3ec87847.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: kaboomzxc/ped#12

**Comment by SemiColonKen** [comment]
Duplicate transaction can only be added when all the other transactions with the same parameters are marked completed
